obstacle_range: 1.5
raytrace_range: 5.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.3
inflation_radius: 2.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: laser, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}